name: 'Maven Deploy Action'
description: 'Deploy Maven artifacts to Maven Central and deploy documentation to GitHub Pages'
author: 'chensoul'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  # Java Environment
  java-version:
    description: 'Java version to use'
    default: '8'
    required: false
  java-distribution:
    description: 'Java distribution'
    default: 'zulu'
    required: false
  
  # Maven Configuration
  server-id:
    description: 'Maven server ID for deployment (matches <server><id> in settings.xml or pom.xml)'
    default: 'central'
    required: false
  maven-args:
    description: 'Additional Maven arguments'
    default: '-ntp -U -B'
    required: false
  maven-profiles:
    description: 'Maven profiles to activate (comma-separated, e.g., central,release)'
    default: 'central'
    required: false
  working-directory:
    description: 'Working directory for Maven'
    default: '.'
    required: false
  
  # Maven Central Credentials
  maven-username:
    description: 'Maven Central username'
    required: true
  maven-password:
    description: 'Maven Central password'
    required: true
  
  # GPG Signing
  gpg-private-key:
    description: 'GPG private key for signing'
    required: true
  gpg-passphrase:
    description: 'GPG passphrase'
    required: true
  
  # GitHub Configuration
  github-token:
    description: 'GitHub token for deploying pages'
    required: false
    default: ''
  
  # Build Options
  skip-tests:
    description: 'Skip running tests'
    default: 'false'
    required: false
  deploy-pages:
    description: 'Deploy documentation to GitHub Pages'
    default: 'true'
    required: false

outputs:
  version:
    description: 'The version that was deployed'
    value: ${{ steps.version.outputs.version }}
  deployed:
    description: 'Whether artifacts were deployed successfully'
    value: ${{ steps.deploy.outputs.deployed }}

runs:
  using: 'composite'
  steps:
    - name: Extract version from tag
      id: version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ "$GITHUB_REF" =~ ^refs/tags/v(.+)$ ]]; then
          TAG_NAME="${BASH_REMATCH[1]}"
        else
          TAG_NAME=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        fi
        
        echo "version=${TAG_NAME}" >> $GITHUB_OUTPUT
        echo "Release version: ${TAG_NAME}"
        
        # Check if this is a SNAPSHOT version
        if [[ "$TAG_NAME" =~ -SNAPSHOT$ ]]; then
          echo "is_snapshot=true" >> $GITHUB_OUTPUT
          echo "⚠️  SNAPSHOT version detected: ${TAG_NAME}"
          echo "📦 GitHub Release and Pages deployment will be skipped for SNAPSHOT versions"
        else
          echo "is_snapshot=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: 'maven'
        server-id: ${{ inputs.server-id }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Build and deploy artifacts
      id: deploy
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SKIP_TESTS_FLAG=""
        [ "${{ inputs.skip-tests }}" == "true" ] && SKIP_TESTS_FLAG="-DskipTests"
        
        PROFILES_FLAG=""
        if [ -n "${{ inputs.maven-profiles }}" ]; then
          PROFILES_FLAG="-P${{ inputs.maven-profiles }}"
        fi
        
        mvn clean deploy site site:stage ${PROFILES_FLAG} ${SKIP_TESTS_FLAG} ${{ inputs.maven-args }}
        echo "deployed=true" >> $GITHUB_OUTPUT
      env:
        MAVEN_USERNAME: ${{ inputs.maven-username }}
        MAVEN_PASSWORD: ${{ inputs.maven-password }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}

    - name: Deploy to GitHub Pages
      if: inputs.deploy-pages == 'true' && inputs.github-token != '' && steps.version.outputs.is_snapshot != 'true'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.working-directory }}/target/staging
        commit_message: "docs: deploy documentation for version ${{ steps.version.outputs.version }}"