name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-local:
    name: Local Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Run local test script
        run: |
          chmod +x ./test-local.sh
          ./test-local.sh
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-project/target/surefire-reports/
            test-project/target/jacoco-results/
          retention-days: 7
      
      - name: Display test summary
        if: always()
        run: |
          echo "## 📊 Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Local tests completed" >> $GITHUB_STEP_SUMMARY
          if [ -f test-project/target/jacoco-results/index.html ]; then
            echo "✅ Coverage report generated" >> $GITHUB_STEP_SUMMARY
          fi

  test-matrix:
    name: Test on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '17', '21', '25']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Test with Java ${{ matrix.java }}
        run: |
          cd test-project
          mvn clean verify
      
      - name: Upload coverage for Java ${{ matrix.java }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-java-${{ matrix.java }}
          path: test-project/target/jacoco-results/
          retention-days: 7

  lint:
    name: Lint Action
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate action.yml
        run: |
          if ! grep -q "^name:" action.yml; then
            echo "❌ action.yml must contain 'name' field"
            exit 1
          fi
          
          if ! grep -q "^description:" action.yml; then
            echo "❌ action.yml must contain 'description' field"
            exit 1
          fi
          
          if ! grep -q "^runs:" action.yml; then
            echo "❌ action.yml must contain 'runs' field"
            exit 1
          fi
          
          echo "✅ action.yml is valid"
      
      - name: Check required files
        run: |
          FILES=(
            "README.md"
            "LICENSE"
            "action.yml"
            "test-local.sh"
          )
          
          for file in "${FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Required file missing: $file"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done
          
          echo "✅ All required files present"

